### ISSUE TITLE
Twoku no longer works

### ISSUE THREAD

**Issue by RShakleford** [worldreboot/twitch-reloaded-roku#8]
I attempted to use the Roku app today and I was greeted with a message that Twoku has moved to a new access code. When I attempted to add the new channel to my account it says that Twoku will now be charging $1 a month for access. I decided to go ahead and add the channel (was only going to see what was going on. I AM NOT PAYING FOR A DAMN  TWITCH APP), but I was then told that the app was not available in my region ( I'm in the US)

**Comment by worldreboot** [comment]
Some people were also having this issue, some people deleted the old twoku app and it worked for them. Others have also said that updating their Roku payment information also worked.

**Comment by Dgc2002** [comment]
I'm having the same issue, removing and adding the TWOKU channel as well as the TTWOKU channel had no effect. I still receive the region availability error. 
  
I have no payment method linked to my account and have no plans to add one.  
  
Is the monthly charge an intentional change?

**Comment by LD143** [comment]
> Is the monthly charge an intentional change?

Is your question, "was all the code added so the dev gets paid accidently researched, typed up, and submitted?"   I mean ... clearly it's intentional.

**Comment by Dgc2002** [comment]
> > Is the monthly charge an intentional change?
> 
> Is your question, "was all the code added so the dev gets paid accidently researched, typed up, and submitted?"   I mean ... clearly it's intentional. 
> 
> 

No need to be snarky. The question is an attempt to clarify the conversation.  
  
When an application suddenly tells you to install a SEPARATE application that then attempts to charge money and even fails to do so did to a regional conflict it's absolutely reasonable to ask of this was intentional on the part of the developers. This could easily be the result of the app owner's account being compromised and a malicious app being uploaded in its place as a way to steal money.  
  
Worldreboots' reply only indicated that others had reported a similar problem, not that any of this(including the new channel code) was intended.

**Comment by LD143** [comment]
The entire clarification was discussed endlessly (and still is) on the Discord. Surely somebody following the project would also follow the channel where "live communication" happens as opposed to a webpage that hasn't been updated in a long time?  Also if there's a credential issue, wouldn't it be safe to assume this would also be compromised as well lending to a response of, "Sure, it's safe - go download it." from what you ASSUME to be the appropriate author?

Honestly - the GitHub hasn't been updated in a while (because it was being monetized behind the scenes) and when it was, the Discord raged out near-instantly. Do yourself a favor - join the Discord and follow the project(s) in real-time.  ;)

Also, my apologies for the snark - it was late and I was tired and slightly annoyed at another thing when I typed that. That'll show me to be on some kind of a forum again!

**Comment by Dgc2002** [comment]
> The entire clarification was discussed endlessly (and still is) on the Discord.  

Yes, I've been part of the discussion on Discord today. The comment you're replying to is from 2 hours before liglius posted his `@here` message on Discord regarding this problem. Prior to that message there's light discussion on the topic but nothing conclusive.  
  
> Surely somebody following the project would also follow the channel where "live communication" happens as opposed to a webpage that hasn't been updated in a long time?   
  
I'm not someone who follows the project. I recently got a Roku TV and found this app/channel and have been using it since then. That's the extent of my interaction with this project.  
  
A problem with Discord is that it's not always easy to identify distinct discussions about certain topics. Issues usually contain a more focused and discoverable conversation about a topic.  
  
_Side note_: Honestly I think the fact that so many projects move support onto Discord will be a big hindrance in the future. The fact is that Discord chats aren't indexed by search engines so a lot of crucial information/discussions aren't reachable through usual means.  
  
> Also if there's a credential issue, wouldn't it be safe to assume this would also be compromised as well lending to a response of, "Sure, it's safe - go download it." from what you ASSUME to be the appropriate author?  
  
That's not a safe assumption, but it is something to be wary of. The developer could be entirely unaware that their Roku account had been compromised. I'm not aware of Roku having the option for multi factor authentication, which automatically makes it more vulnerable than GitHub. Regardless, making contact with a developer through multiple venues is a way to ensure the actual developer is notified.  
  
I also had no intention to attempt to install the new channel until all of this was cleared up.
