### ISSUE TITLE
Commercial break after (almost) every channel change

### ISSUE THREAD

**Issue by DanStro** [worldreboot/twitch-reloaded-roku#9]
Just about every time I change to a new channel I get a screen saying something like "Commercial in progress..." and a time counts down from 15 seconds. There have  been a couple of times where this didn't happen and the channel just opened without this screen. These were not channels that I am subscribed to so it isn't that.

Also, every once in a while it gets caught in a loop where this screen just keeps coming up and when the counter reaches zero it resets to 14. This has only happened to me on the RiffTraks channel.

**Comment by chucktheviking** [comment]
This has nothing to do with the Roku App. This is Twitch.tv's new "automated mid-roll ads" forced feature. Since the Roku App doesn't actually log into your account, the app is seeing an Ad as soon as it enters a channel. If you see many of these screens happen in a row, it is because the channel is running an Ad break. Usually channels run them for 60-180 seconds.

**Comment by DanStro** [comment]
I didn't realize that, sorry.
